Fix Linux build
Seeing the following linker error on Linux since commit 674b37e8e6:
../.libs/libhwcomposer.so: undefined reference to `hwcomposer::NestedDisplay::NestedDisplay()'

Just need to add the new file to the Makefile

Jira: None
Test: Build passes on Linux

Signed-off-by: Kevin Strasser <kevin.strasser@intel.com>