Fix hwc compilation error due to libva2.0 master upgrade
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-57070
Change-Id: Ifa8663e178b48fdb24ad35d1de71c26b643da374
Signed-off-by: Chew, Tong Liang <tong.liang.chew@intel.com>
Reviewed-on: https://android.intel.com:443/614763